server:
  port: 8080

spring:
  application:
    name: sso-demo
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: fHFs7dtCzmz3rLfQ96jl5fkizBEUvlqi
            client-secret: OTYYxfNCQJUff8Pk9frAPqEUnsv6R29ErKaF13DGufYq_spkCPXKCW9hfrvU05X0
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth0:
            issuer-uri: https://dev-xns558dobru7f6t5.us.auth0.com/
            user-name-attribute: name

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
